Support 2.0 deferred props
inertiajs/inertia-django pull request #56
Opened 2024-12-26 19:00 UTC by mrfolksy

As of version 2.0, Inertia supports the ability to defer the fetching of props until after the page has been initially rendered. Essentially this is similar to the concept of `Lazy props` however Inertia provides convenient frontend components to automatically fetch the deferred props after the page has initially loaded, instead of requiring the user to initiate a reload. For more info see [Deferred props](https://inertiajs.com/deferred-props) in the Inertia documentation.

This PR introduces a `defer` function to mark props to be deferred, examples below

```python
from inertia import defer, inertia

@inertia('ExampleComponent')
def example(request):
  return {
    'name': lambda: 'Brandon', # this will be rendered on the first load as usual
    'data': defer(lambda: some_long_calculation()), # this will only be run after the frontend has initially loaded and inertia requests this prop
  }
```
#### Grouping requests
By default, all deferred props get fetched in one request after the initial page is rendered, but you can choose to fetch data in parallel by grouping props together.

```python
from inertia import defer, inertia

@inertia('ExampleComponent')
def example(request):
  return {
    'name': lambda: 'Brandon', # this will be rendered on the first load as usual
    'data': defer(lambda: some_long_calculation()),
    'data1': defer(lambda: some_long_calculation1(), 'group'), 
    'data2': defer(lambda: some_long_calculation1(), 'group'),
  }

2024-12-28 02:55 UTC, BrandonShar requested changes
Thank you @mrfolksy this looks great! I just have a couple minor changes I'd like before we merge, but the structure looks perfect.

2024-12-28 02:55 UTC, BrandonShar commented on inertia/http.py
> +            _deferred_props.setdefault(prop.group, []).append(key)
this is almost too clever, it took me a few reads :smile: I like it though!

2024-12-28 02:55 UTC, BrandonShar commented on inertia/utils.py
> +    return base_model_to_dict(model, exclude=("password",))
looks like some formatting got messed up in this file

2024-12-28 02:55 UTC, BrandonShar commented on inertia/utils.py
> +def defer(prop, group=None):
The [laravel](https://github.com/inertiajs/inertia-laravel/blob/0259e37f802bc39c814c42ba92c04ada17921f70/src/ResponseFactory.php#L112) and [rails](https://github.com/inertiajs/inertia-rails/blob/8c749e32e568b4acb54357d05d9a85e2f12b6ea1/lib/inertia_rails/defer_prop.rb#L12) versions use a default group of "default", could we add that here?

2024-12-28 02:55 UTC, BrandonShar commented on README.md
> +    'data1': defer(lambda: some_long_calculation1(), 'group'),
super small thing, could we add a named key to the example?

```python
'data1': defer(lambda: some_long_calculation1(), group='group')
```

2024-12-28 02:55 UTC, BrandonShar commented on inertia/tests/test_rendering.py
> +class DeferredPropsTestCase(InertiaTestCase):
Great test cases for the base case! Could we also add two additional tests in this TestCase to verify that the props are returned correctly when they're requested via the deferred request? I think they will end up looking something like the `LazyPropsTestCase#test_lazy_props_are_included_when_requested` test above.

2024-12-30 19:50 UTC, mrfolksy commented
> Thank you @mrfolksy this looks great! I just have a couple minor changes I'd like before we merge, but the structure looks perfect.

Thanks for the feedback @BrandonShar, appreciate it, I’ll make the amendments over the next few days.

2025-01-02 08:01 UTC, mrfolksy commented on inertia/utils.py
> +    return base_model_to_dict(model, exclude=("password",))
Thanks for spotting this, I realised whilst making this change that my default formatting tools were messing things up, so switched the off. Missed this file!

Also, totally missed that the indent was set to 2 spaces, 4 spaces is more typical as it is the PEP8 recommendation. The project may want to consider adding a formatting tool such as `black` or `ruff` at some point. If you are open to this I could raise a PR....

2025-01-02 08:54 UTC, mrfolksy commented
@BrandonShar, changes have been made, let me know if there are any other changes needed.

2025-01-04 18:03 UTC, BrandonShar approved these changes

2025-01-04 18:11 UTC, BrandonShar commented
Thanks @mrfolksy ! I just corrected conflicts so if you could take a quick look and make sure my commit looks right we'll be good to merge!

Also, some type of formatting tool would be awesome here. If you have one you've had success with, I'd be happy to merge it!

2025-01-04 19:04 UTC, merged

2025-01-04 19:04 UTC, BrandonShar commented
I went ahead and merged it because I'm working on some things right now and I didn't want to conflict again :smile: